language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t parmish/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parmish/docker-react npm run test
